version: '3'
services:
  mysql:
    image: mysql:8.0.25
    container_name: social-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: social
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '1'
      LANG: C.UTF-8
      TZ: Asia/Ho_Chi_Minh
    ports:
      - 13306:3306

  redis:
    image: 'redis:6-alpine'
    container_name: social-redis
    ports:
      - 16379:6379
